### ISSUE TITLE
Some minor bugs from testing

### ISSUE THREAD

**Issue by Rebecca3535** [Scarso327/AltisLife-Framework#461] opened 2024-12-16 22:03 UTC
List of known bugs reported from live server.

Sometimes hunger stops going down and the player dies from hunger and thirst.( be stuck at 50% )
sometimes backpack space does not upgrade with a new backpack.

messages from tablets sometimes dont let you send unless you remove all messages in inbox.
https://medal.tv/games/arma-3/clips/jinMQQ1H6dxbX25PY?invite=cr-MSxETnAsMTY0NTc0MjU1LA

radiation does not work. you get the achievement but no health damage ever happens.
freight mission destinations are broke.
![20241216053526_1](https://github.com/user-attachments/assets/cf254022-7b40-43c6-90c6-fe0cf74ff69c)

after dying player has stamina.

As said before the work bench is not working. tested it after having blue prints but I am being told it does not work.

**Comment by Scarso327** [comment] 2024-12-16 22:49
Hi @Rebecca3535 

#452 - This should fix the issue you had with hunger not moving

#463 - This fixes the workbench near check, I recommend adding #459 as it adds a "Requires Workbench" line to the Tablet UI

#465 - This fixes the sending message button being disabled

I'd need more information on how to reproduce the backpack issue. Video evidence would be perfect.

**Comment by Rebecca3535** [comment] 2024-12-17 22:55
Hello @Scarso327 Update on the weapon duping (Putting things in car and alt f4ing/disconnect) works. you can no longer dupe weapons/clothing. But can still dupe virtual items. Also prison release now works also thanks so much for that.

Side bugs. Raidiation does no damaging effect. And the metal detector trigger does not do anything tho its not priority.

With these new changes i added them and uploaded it to my server and its broke the server fully. I triple checked all file locations and whats confused me is all the files are the same. So its something within the code. Best ask you. This is what comes up in the web consol (See screen shot) . Server has no slots to join etc. So went back to an old save. So no sure if the new fixes work till i can get the server running after fixing this error.  Cheers!!

![Screenshot 2024-12-17 224921](https://github.com/user-attachments/assets/e23b3d19-a68b-4c0a-b1d7-66dd53df085a)

**Comment by Scarso327** [comment] 2024-12-18 17:22
@Rebecca3535 

If you go into CfgSettings, what version is listed near the top? You may be on an older version that is missing things from the current development build. Are you using git to just making changes manually? If you've only made changes to the map and configs it might be easier to drop your configs and map onto the latest files from the master branch.

**Comment by Rebecca3535** [comment] 2024-12-18 17:34
Thanks for the reply!   Its framework_version = "1.1.2";    All the changes i done before worked fine.  I download all the files and the replace the old ones with the new ones in the folders and the PBO it and upload.

**Comment by Rebecca3535** [comment] 2024-12-18 17:45
> The current master branch has had many changes since that version. You can view exact changes [here](https://github.com/Scarso327/AltisLife-Framework/compare/v1.1.2...v1.2.2). Near the top of the list you can see the save cart features being added.
> 
> I recommend using github desktop as you can then pull down from the remote master branch as changes are made at the very least and ensure you're kept up to date.

I see. This is why i need a dev, I have made many changes like prices. removed some jets and a lot of map changes and a change to the prison (put in prison) GPS that works with the priosn i built. Is it possable to keep all these changes. Or chall i just upload the newer updated files in my folders?

**Comment by Scarso327** [comment] 2024-12-18 17:57
Do you know the exact changes you've made to the mission?

**Comment by Rebecca3535** [comment] 2024-12-18 17:59
A lot to the map. and i can look at what i have changed and copy it all over. take a few hours tho.

**Comment by Scarso327** [comment] 2024-12-18 18:02
You shouldn't need to copy anything over. No map changes have been made since your version. 

Have you edited any configs like `CfgStores`? 

You'll need to update your database as well using https://github.com/Scarso327/AltisLife-Framework/blob/master/Server%20Side/Database/Migrations/1.2.0.sql

**Comment by Rebecca3535** [comment] 2024-12-18 18:14
I just checked and seems i am missing 4 whole files in stores. Strange thing is tho the surrent one that is up and working now is also missing 4 files in stores. so im more confused haha

**Comment by Scarso327** [comment] 2024-12-19 20:46
Hi @Rebecca3535 

Have you had any luck in progressing this?

**Comment by Scarso327** [comment] 2024-12-20 14:59
@Rebecca3535 All reproducible issues reported here are now fixed. If you get more info on the backpack size not always updating feel free to create a new issue for it. Also stick to one issue per bug to help manage it all thank you!

**Closed by Scarso327** 2024-12-20 14:59 UTC
Labels: Bug

**Comment by Rebecca3535** [comment] 2024-12-24 02:03
New bug list

tasers sometimes kill the player rather than tasing them

Option to flip vehicle is no longer there

Unlimited stamina goes away after death sometimes

Unable to cuff players when they are down. Leading them to shoot when revived. This ruined RP for police then they are trying to ticket or try to jail them

Kavala PD haunted. Whitelisted police doors keep opening randomly

House storage for guns bags etc does not save in the house after a server restart, sometimes virtual too. 

Virtual items can still be duped.  I think.
